base_config: "preprocess_base.yaml"
preprocessor: "LJSpeech"

###################
# Data Directories
###################

raw_data_dir: "D:/Speech Data/LJ/LJSpeech-1.1"
data_dir: "D:/Speech Data/LJ/LJSpeech-1.1/Processed_Data"
#raw_data_dir: "C:/Users/zakww/OneDrive/Documents/Speech Data/Test"
#data_dir: "C:/Users/zakww/OneDrive/Documents/Speech Data/Test/Processed_Data"

###################
# Text Cleaner
###################

cleaner: "Simple English"

###################
# Text to Phoneme
###################

text_to_phoneme: "Simple English"

###################
# Aligner
###################

silence_boost: 10
mfa_processes: 20

