_target_: src.models.vocoder.VocoderLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: max
  factor: 0.1
  patience: 10

net:
  _target_: src.models.vocoders.wavenet.WaveNetVocoder
  filter_width: 2
  dilation_power: 2
  dilation_max_power: 8
  dilation_depth: 12
  residual_channels: 16
  dilation_channels: 32
  skip_channels: 16
  n_mels: 80
  local_condition_channels: null

# compile model for faster training with pytorch 2.0
compile: false