_target_: src.models.simple_vocoder.SimpleVocoderLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_vocoder.SimpleVocoder
  input_size: 80
  lin1_size: 256
  lin2_size: 256
  lin3_size: 256
  output_size: 1

# compile model for faster training with pytorch 2.0
compile: false