base_config: "../config_base.yaml"
task: "vocoder"
vocoder: "FastDiff"

model_config: "FastDiff/FastDiff_model.yaml"
data_dir: "D:/Speech Data/LJ/LJSpeech-1.1/Processed_Data"
work_dir: "../models"
save_top_k: 5
save_last_k: 10
load_ckpt: true

trainable: true
train: true

batch_size: 4
shuffle: true

num_workers: 4
use_gpu: true
pin_memory: true

accumulate_gradient: 1